tickit:
  outputs:
    prod:
      database: awsdatacatalog
      region_name: ap-northeast-1
      s3_data_dir: s3://nijigen-plot-dbt-tables
      s3_staging_dir: s3://aws-athena-query-results-875141268485-ap-northeast-1
      schema: tickit 
      threads: 3
      type: athena
      work_group: primary # あとで適切なwork_groupにする 
      num_retries: 0
      num_boto3_retries: 1
      aws_profile_name: dbt-local
  target: prod
