version: 0.2

env:
  variables:
    DATA_PIPELINE_RESOURCE_S3_BUCKET: nijipro-dbt-resources-test
    CLOUDFORMATION_ROLE_NAME: cloudformation-dbt-athena-community-resources-service-role
    DWH_STACK_NAME: 'dbt-infrastructure'

phases:
  install:
    runtime-versions:
      python: 3.11.4
    commands:
      - python3 --version
      - sudo apt-get update
      - curl -sSf https://rye.astral.sh/get | RYE_NO_AUTO_INSTALL=1 RYE_INSTALL_OPTION="--yes" bash
      - . "$HOME/.rye/env"
      - rye --version
      - rye sync --no-dev --no-lock
  pre_build:
    commands:
      - aws --version
      - aws s3 sync --exact-timestamps --delete aws/stepfunctions/ s3://$DATA_PIPELINE_RESOURCE_S3_BUCKET/stepfunctions/
      - bash script/create_zip_files.sh
      - AWSServiceExecuteResultNotificationParam=$(aws s3api list-object-versions --bucket $DATA_PIPELINE_RESOURCE_S3_BUCKET --prefix lambda/aws_service_execute_result_notification.zip | jq -r '.Versions[0].VersionId')
      - DbtBatchParam=$(aws s3api list-object-versions --bucket $DATA_PIPELINE_RESOURCE_S3_BUCKET --prefix stepfunctions/dbt_batch.yml | jq -r '.Versions[0].VersionId')
  build:
    commands:
      - ORIGINAL_DIR=$(pwd)
      - echo "dbt Docker Image Build & Push"
      - echo $AWS_ACCOUNT_ID
      - docker build -t dbt-batch .
      - >
        aws ecr get-login-password --region ap-northeast-1 |
        docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com
      - aws ecr describe-repository-name dbt-batch || aws ecr create-repository --repository-name dbt-batch --region ap-northeast-1 --image-scanning-configuration scanOnPush=true --image-tag-mutability MUTABLE
      - docker tag dbt-batch:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/dbt-batch:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/dbt-batch:latest
      - cd $ORIGINAL_DIR
  post_build:
    commands:
      - echo deploy data pipeline infrastructure
      - aws cloudformation package --template-file aws/cloudformation/$DWH_STACK_NAME.yml --s3-bucket $DATA_PIPELINE_RESOURCE_S3_BUCKET --s3-prefix cloudformation/package --output-template-file /tmp/$DWH_STACK_NAME.yml --force-upload
      - |
        aws cloudformation deploy --no-fail-on-empty-changeset --template-file /tmp/$DWH_STACK_NAME.yml --stack-name $DWH_STACK_NAME --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/$CLOUDFORMATION_ROLE_NAME --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM \
        --parameter-overrides \
        "AWSServiceExecuteResultNotificationParam=$AWSServiceExecuteResultNotificationParam" \
        "DbtBatchParam=$DbtBatchParam" \
